// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qepeabqhhpttneoohfyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcGVhYnFoaHB0dG5lb29oZnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDc1MjQsImV4cCI6MjA1NDY4MzUyNH0.d-yUS62c60NZBIaUseZV6dQ_ru_vw-ECXinats6VFII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);